In [1]:
# import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
boces_path = "/Users/belladu/Desktop/IDS701_Final+Project/unifying-data-science-2023-project-grupo9/Data_clean_merge/boces_2018_2019_2021_2022.csv"
scienc_2019_path = "/Users/belladu/Desktop/IDS701_Final+Project/unifying-data-science-2023-project-grupo9/Data_clean_merge/df_science_2019.csv"
scienc_2022_path = "/Users/belladu/Desktop/IDS701_Final+Project/unifying-data-science-2023-project-grupo9/Data_clean_merge/df_science_2022.csv"
ela_2019_path = "/Users/belladu/Desktop/IDS701_Final+Project/unifying-data-science-2023-project-grupo9/Data_clean_merge/df_ela_2019.csv"
ela_2022_path = "/Users/belladu/Desktop/IDS701_Final+Project/unifying-data-science-2023-project-grupo9/Data_clean_merge/df_ela_2022.csv"
math_2019_path = "/Users/belladu/Desktop/IDS701_Final+Project/unifying-data-science-2023-project-grupo9/Data_clean_merge/df_math_2019.csv"
math_2022_path = "/Users/belladu/Desktop/IDS701_Final+Project/unifying-data-science-2023-project-grupo9/Data_clean_merge/df_math_2022.csv"

In [15]:
# read science and math 2019 and 2022 data
df_science_2019 = pd.read_csv(scienc_2019_path)
df_science_2022 = pd.read_csv(scienc_2022_path)
df_math_2019 = pd.read_csv(math_2019_path)
df_math_2022 = pd.read_csv(math_2022_path)
df_ela_2019 = pd.read_csv(ela_2019_path)
df_ela_2022 = pd.read_csv(ela_2022_path)
df_boces = pd.read_csv(boces_path)

df_science_2019.head()

/var/folders/_1/lp5kp6tj2lsd_ry1fksy95kc0000gn/T/ipykernel_38959/4133974425.py:3: DtypeWarning: Columns (11,12,13,15,19,21,22,24,28,30,31,33,37,39,40,42,46,48,49,51,55,57,58,60,64,66,67,69,73,75,76,78,82,84,85,87,91,93,94,96,100,102,103,105,109,111,112,114,118,120,121,123,127,129) have mixed types. Specify dtype option on import or set low_memory=False.
  df_science_2022 = pd.read_csv(scienc_2022_path)
/var/folders/_1/lp5kp6tj2lsd_ry1fksy95kc0000gn/T/ipykernel_38959/4133974425.py:5: DtypeWarning: Columns (11,12,13,15,19,21,22,24,28,30,31,33,37,39,40,42,46,48,49,51,55,57,58,60,64,66,67,69,73,75,76,78,82,84,85,87,91,93,94,96,100,102,103,105,109,111,112,114,118,120,121,123,127,129) have mixed types. Specify dtype option on import or set low_memory=False.
  df_math_2022 = pd.read_csv(math_2022_path)


ENTITY_CD         ENTITY_NAME  YEAR   ASSESSMENT_NAME NOT_TESTED  \
0          1  NYC Public Schools  2018          Science4       8549   
1          1  NYC Public Schools  2018          Science8      23690   
2          1  NYC Public Schools  2018   RegentsScience8          s   
3          1  NYC Public Schools  2018  CombinedScience       23690   
4          1  NYC Public Schools  2018        Science4_8      32239   

   NUM_TESTED NUM_PROF PER_PROF TOTAL_SCALE_SCORES MEAN_SCORE  ...  \
0       68089    59021       87            5510492         81  ...   
1       47519    25375       53            3062957         64  ...   
2       14463    11338       78                NaN        NaN  ...   
3       61982    36713       59            3062957         49  ...   
4      130071    95734       74            8573449         66  ...   

  Not Economically Disadvantaged_NUM_PROF  \
0                                   15780   
1                                    6860   
2                                    4929   
3                                     NaN   
4                                     NaN   

  Not Economically Disadvantaged_NUM_TESTED  \
0                                   16622.0   
1                                    9907.0   
2                                    5529.0   
3                                       NaN   
4                                       NaN   

  Not Economically Disadvantaged_PER_PROF  \
0                                      95   
1                                      69   
2                                      89   
3                                     NaN   
4                                     NaN   

   Not Economically Disadvantaged_TOTAL_SCALE_SCORES  \
0                                            1451579   
1                                             707668   
2                                                NaN   
3                                                NaN   
4                                                NaN   

  Students with Disabilities_MEAN_SCORE Students with Disabilities_NOT_TESTED  \
0                                    74                                  6412   
1                                    54                                  7136   
2                                   NaN                                     s   
3                                   NaN                                   NaN   
4                                   NaN                                   NaN   

  Students with Disabilities_NUM_PROF Students with Disabilities_NUM_TESTED  \
0                               11052                               14793.0   
1                                2910                               10589.0   
2                                 537                                1328.0   
3                                 NaN                                   NaN   
4                                 NaN                                   NaN   

  Students with Disabilities_PER_PROF  \
0                                  75   
1                                  27   
2                                  40   
3                                 NaN   
4                                 NaN   

   Students with Disabilities_TOTAL_SCALE_SCORES  
0                                        1087759  
1                                         567837  
2                                            NaN  
3                                            NaN  
4                                            NaN  

[5 rows x 88 columns]

In [16]:
# get the unique EntityID in 2019
df_science_2019_unique = df_science_2019['ENTITY_CD'].unique()
df_science_2019_unique

array([           1,            2,            3, ..., 590901060008,
       660900010026, 660900010027])

In [17]:
# add a subject label to the 2019 data
df_science_2019['Subject'] = 'Science'
df_math_2019['Subject'] = 'Math'
df_ela_2019['Subject'] = 'ELA'

# add a year label to the 2019 data
df_science_2019['YEAR'] = 2019
df_math_2019['YEAR'] = 2019
df_ela_2019['YEAR'] = 2019

# add a subject label to the 2022 data
df_science_2022['Subject'] = 'Science'
df_math_2022['Subject'] = 'Math'
df_ela_2022['Subject'] = 'ELA'

# add a year label to the 2022 data
df_science_2022['YEAR'] = 2022
df_math_2022['YEAR'] = 2022
df_ela_2022['YEAR'] = 2022



In [18]:
# combine the 2019 and 2022 data
df_science = pd.concat([df_science_2019, df_science_2022], axis=0)
df_math = pd.concat([df_math_2019, df_math_2022], axis=0)
df_ela = pd.concat([df_ela_2019, df_ela_2022], axis=0)

# combine the science, math, and ela data
df_subject = pd.concat([df_science, df_math, df_ela], axis=0)

# get the unique EntityID in 2019
df_subject_unique = df_subject['ENTITY_CD'].unique()
df_subject_unique

array([           1,            2,            3, ..., 661201060006,
       662401060010, 331400011610])

In [19]:
df_boces = pd.read_csv(boces_path)
df_boces.head()

ENTITY_CD                     SCHOOL_NAME  YEAR  DISTRICT_CD  \
0  10100010014        MONTESSORI MAGNET SCHOOL  2018    1010001.0   
1  10100010016    PINE HILLS ELEMENTARY SCHOOL  2018    1010001.0   
2  10100010018       DELAWARE COMMUNITY SCHOOL  2018    1010001.0   
3  10100010019  NEW SCOTLAND ELEMENTARY SCHOOL  2018    1010001.0   
4  10100010023     ALBANY SCHOOL OF HUMANITIES  2018    1010001.0   

                 DISTRICT_NAME  BOCES_CD  \
0  ALBANY CITY SCHOOL DISTRICT       190   
1  ALBANY CITY SCHOOL DISTRICT       190   
2  ALBANY CITY SCHOOL DISTRICT       190   
3  ALBANY CITY SCHOOL DISTRICT       190   
4  ALBANY CITY SCHOOL DISTRICT       190   

                             BOCES_NAME  COUNTY_CD COUNTY_NAME  NEEDS_INDEX  \
0  BOCES ALBANY-SCHOH-SCHENECTADY-SARAT          1      ALBANY          3.0   
1  BOCES ALBANY-SCHOH-SCHENECTADY-SARAT          1      ALBANY          3.0   
2  BOCES ALBANY-SCHOH-SCHENECTADY-SARAT          1      ALBANY          3.0   
3  BOCES ALBANY-SCHOH-SCHENECTADY-SARAT          1      ALBANY          3.0   
4  BOCES ALBANY-SCHOH-SCHENECTADY-SARAT          1      ALBANY          3.0   

   INSTITUTION_ID  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN

In [20]:
# get the unique EntityID in df_boces
df_boces_unique = df_boces['ENTITY_CD'].unique()
df_boces_unique

array([ 10100010014,  10100010016,  10100010018, ..., 680601060005,
       680801040001, 680801040002])

In [21]:
# check the length of the unique EntityID in df_bocesa and df_subject
len(df_boces_unique), len(df_subject_unique)

# check how much overlap there is between the two
len(set(df_boces_unique).intersection(set(df_subject_unique)))

3753

In [25]:
# add the columns in bocese to the subject data frame using EntityID as the key
df_subject = pd.merge(df_subject, df_boces, on='ENTITY_CD', how='left')

# check the number of missing values in each column
df_subject.isnull().sum()


ENTITY_CD               0
ENTITY_NAME             0
YEAR_x                  0
ASSESSMENT_NAME         0
NOT_TESTED             20
                    ...  
BOCES_NAME         350349
COUNTY_CD           74569
COUNTY_NAME         74569
NEEDS_INDEX         74605
INSTITUTION_ID     441581
Length: 141, dtype: int64

In [26]:
df_subject.head()

ENTITY_CD         ENTITY_NAME  YEAR_x   ASSESSMENT_NAME NOT_TESTED  \
0          1  NYC Public Schools    2019          Science4       8549   
1          1  NYC Public Schools    2019          Science8      23690   
2          1  NYC Public Schools    2019   RegentsScience8          s   
3          1  NYC Public Schools    2019  CombinedScience       23690   
4          1  NYC Public Schools    2019        Science4_8      32239   

   NUM_TESTED NUM_PROF PER_PROF TOTAL_SCALE_SCORES MEAN_SCORE  ...  \
0       68089    59021       87            5510492         81  ...   
1       47519    25375       53            3062957         64  ...   
2       14463    11338       78                NaN        NaN  ...   
3       61982    36713       59            3062957         49  ...   
4      130071    95734       74            8573449         66  ...   

  SCHOOL_NAME YEAR_y DISTRICT_CD  DISTRICT_NAME BOCES_CD BOCES_NAME COUNTY_CD  \
0         NaN    NaN         NaN            NaN      NaN        NaN       NaN   
1         NaN    NaN         NaN            NaN      NaN        NaN       NaN   
2         NaN    NaN         NaN            NaN      NaN        NaN       NaN   
3         NaN    NaN         NaN            NaN      NaN        NaN       NaN   
4         NaN    NaN         NaN            NaN      NaN        NaN       NaN   

  COUNTY_NAME NEEDS_INDEX  INSTITUTION_ID  
0         NaN         NaN             NaN  
1         NaN         NaN             NaN  
2         NaN         NaN             NaN  
3         NaN         NaN             NaN  
4         NaN         NaN             NaN  

[5 rows x 141 columns]